const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('prototypes/m1/index.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
const elements=new Map(),listeners={};const element=()=>({textContent:'',hidden:false,value:1,checked:false,getContext:()=>({})});
const context=vm.createContext({console,performance:{now:()=>0},requestAnimationFrame:()=>{},localStorage:{getItem(){throw Error('denied')},setItem(){throw Error('denied')}},document:{querySelector(s){if(!elements.has(s))elements.set(s,element());return elements.get(s)},addEventListener(){}},window:{addEventListener(k,f){listeners[k]=f}}});vm.runInContext(source,context);
const run=s=>vm.runInContext(s,context);let passed=0;function test(name,fn){run('start()');fn();console.log('PASS',name);passed++}const ticks=s=>run(`for(let i=0;i<${s*120};i++)step(STEP)`);
test('idle hiding gives zero score and safe spawn',()=>{ticks(119);assert.equal(run('g.irritation+g.dodges+g.collateral'),0);assert.equal(run('g.mode'),'play');ticks(2);assert.equal(run('g.mode'),'result')});
test('ear diminishing visits 30 / 15 / 0',()=>{run('g.x=EAR.x;g.y=EAR.y;g.provoked=false');for(let visit=0;visit<3;visit++){run('g.earAway=1;g.state="recovery";g.timer=20');ticks(3.1)}assert.ok(Math.abs(run('g.irritation')-45)<1e-6)});
test('sandwich landing commitment and diminished visits',()=>{run('g.x=FOOD.x;g.y=FOOD.y');for(let i=0;i<3;i++){run('action("KeyE");g.state="recovery";g.timer=20');ticks(.7);run('action("KeyE")')}assert.equal(run('g.irritation'),150)});
test('pause freezes strike and clears input',()=>{run('g.state="strike";g.timer=.1;keys.add("KeyD");pause()');const t=run('g.time');ticks(5);assert.equal(run('g.time'),t);assert.equal(run('keys.size'),0);assert.equal(run('g.state'),'strike')});
test('focus loss pauses',()=>{listeners.blur();assert.equal(run('g.mode'),'pause')});
test('cabinet blocks perception and strike',()=>{assert.equal(run('lineClear(200,335)'),false);run('g.angle=Math.PI;g.reach=500');assert.equal(run('inside(200,335)'),false)});
test('swept collision catches fast crossing and burst is vulnerable',()=>{run('g.angle=0;g.reach=255');assert.equal(run('swept(700,200,700,450)'),true);run('g.x=700;g.y=335;g.state="strike";g.timer=.15;g.attackTier=2;g.burst=.1');ticks(.01);assert.equal(run('g.mode'),'result')});
test('committed target cannot home',()=>{run('g.x=650;g.y=335;g.state="windup";g.timer=0;g.reach=255');ticks(1/120);const a=run('g.angle');run('g.x=600;g.y=530');ticks(.05);assert.equal(run('g.angle'),a)});
test('human-only lamp attribution once',()=>{run('g.x=LAMP.x;g.y=LAMP.y');ticks(.1);assert.equal(run('g.collateral'),0);run('g.x=800;g.y=500;g.state="strike";g.angle=0;g.reach=255;g.attackTier=2;g.timer=.15');ticks(.2);assert.equal(run('g.collateral'),400);run('g.state="strike";g.timer=.15');ticks(.2);assert.equal(run('g.collateral'),400)});
test('scripted bait → dodge → lamp → exit → restart route',()=>{run('g.x=700;g.y=335;g.anger=50;g.provoked=true');ticks(.88);assert.equal(run('g.state'),'windup');run('keys.add("KeyS");action("Space")');ticks(.5);run('keys.clear()');assert.equal(run('g.broken'),true);assert.equal(run('g.mode'),'play');run('g.x=1010;g.y=210;g.vx=g.vy=0');ticks(.8);assert.equal(run('g.mode'),'result');assert.ok(run('g.bonus')>0);run('start()');assert.equal(run('g.collateral'),0)});
test('30 / 60 / 120 FPS replay equivalence',()=>{const outcomes=[];for(const fps of [30,60,120]){run('start();keys.add("KeyD")');run(`for(let i=0;i<${fps*2};i++)advance(1/${fps})`);outcomes.push(run('[g.x,g.y,g.irritation,g.time]'))}for(const o of outcomes)for(let i=0;i<o.length;i++)assert.ok(Math.abs(o[i]-outcomes[0][i])<1e-6);console.log('replay',JSON.stringify(outcomes))});
test('scoring agrees at 30 / 60 / 120 FPS',()=>{for(const fps of [30,60,120]){run('start();g.x=EAR.x;g.y=EAR.y;g.state="recovery";g.timer=10');run(`for(let i=0;i<${fps*3};i++)advance(1/${fps})`);assert.ok(Math.abs(run('g.irritation')-30)<1e-6)}});
test('rapid reset and ten simulated minutes',()=>{for(let i=0;i<100;i++)run('start()');for(let i=0;i<5;i++){run('start()');ticks(121);assert.equal(run('g.mode'),'result')}assert.equal(run('g.collateral'),0)});
test('complete spawn to sandwich to escape using only input',()=>{
 function move(x,y,max=8){for(let i=0;i<max*120;i++){const [px,py,vx,vy]=run('[g.x,g.y,g.vx,g.vy]');if(Math.hypot(px-x,py-y)<10&&Math.hypot(vx,vy)<35){run('keys.clear()');return}run('keys.clear()');const ex=x-px-vx*.10,ey=y-py-vy*.10;if(Math.abs(ex)>4)run(`keys.add('${ex>0?'KeyD':'KeyA'}')`);if(Math.abs(ey)>4)run(`keys.add('${ey>0?'KeyS':'KeyW'}')`);run('step(STEP)');assert.equal(run('g.mode'),'play')}throw Error('waypoint failed '+x+','+y)}
 move(560,535);move(560,485);run('action("KeyE")');ticks(.62);assert.equal(run('g.irritation'),100);run('action("KeyE");keys.add("KeyD");action("Space")');ticks(.4);run('keys.clear()');move(900,500);move(1010,210);ticks(.8);assert.equal(run('g.mode'),'result');assert.ok(run('g.bonus')>0);
});
test('normal spawn to intentional lamp bait and escape, input only',()=>{
 run('var recordedInputs=[];var lastInput="";var normalStep=step;var normalAction=action;step=function(dt){const input=[...keys].sort().join(",");if(input!==lastInput){recordedInputs.push([g.steps,[...keys],null]);lastInput=input}normalStep(dt)};action=function(code){recordedInputs.push([g.steps,[...keys],code]);normalAction(code)}');
 function move(x,y,max=8){for(let i=0;i<max*120;i++){const [px,py,vx,vy]=run('[g.x,g.y,g.vx,g.vy]');if(Math.hypot(px-x,py-y)<10&&Math.hypot(vx,vy)<35){run('keys.clear()');return}run('keys.clear()');const ex=x-px-vx*.06,ey=y-py-vy*.06;if(Math.abs(ex)>4)run(`keys.add('${ex>0?'KeyD':'KeyA'}')`);if(Math.abs(ey)>4)run(`keys.add('${ey>0?'KeyS':'KeyW'}')`);run('step(STEP)');assert.equal(run('g.mode'),'play','died en route to '+x+','+y+' '+run('JSON.stringify({x:g.x,y:g.y,time:g.time,state:g.state,timer:g.timer,angle:g.angle,anger:g.anger,swats:g.swats})'))}throw Error('waypoint failed')}
 move(560,535);move(560,485);run('action("KeyE")');ticks(.62);run('action("KeyE");keys.add("KeyD");action("Space")');ticks(.4);run('keys.clear()');move(850,480);ticks(.7);move(680,335);
 for(let i=0;i<600;i++){if(run('g.state==="windup"&&g.timer<=.29'))break;run('step(STEP)')}
 assert.equal(run('g.attackTier'),2);assert.ok(run('inside(LAMP.x,LAMP.y,20)'));run('keys.add("KeyS");action("Space")');ticks(.5);run('keys.clear()');assert.equal(run('g.broken'),true);assert.equal(run('g.mode'),'play');move(930,500);move(1010,210);ticks(.8);assert.equal(run('g.mode'),'result');assert.ok(run('g.bonus')>0);console.log('natural lamp route',run('JSON.stringify({time:g.time,irritation:g.irritation,dodges:g.dodges,collateral:g.collateral,bonus:g.bonus})'));
 if(process.argv.includes('--record-demo'))fs.writeFileSync('test-results/demo.json',run('JSON.stringify(recordedInputs)'));
 run('step=normalStep;action=normalAction');
});
test('snappy release stops within 18 units and 0.2 seconds',()=>{run('keys.add("KeyD")');ticks(.5);run('keys.clear()');const x=run('g.x');ticks(.2);assert.ok(run('g.x')-x<18);assert.ok(run('Math.hypot(g.vx,g.vy)')<4)});
test('moving alongside cabinet slides without freezing',()=>{run('g.x=BLOCK.x-10;g.y=300;keys.add("KeyD");keys.add("KeyS")');ticks(.3);assert.ok(run('g.y')>340);assert.ok(run('g.x<=BLOCK.x-9'))});
test('standing beside a harmless swat cannot farm dodge score',()=>{run('g.x=750;g.y=500;g.state="strike";g.angle=0;g.reach=205;g.attackTier=1;g.timer=.15;g.near=false');ticks(.2);assert.equal(run('g.dodges'),0)});
test('watch example completes and never records a player score',()=>{const best=run('prefs.best');run('prefs.sensitivity=.8;startDemo()');ticks(12);assert.equal(run('g.mode'),'result');assert.equal(run('g.broken'),true);assert.ok(run('g.bonus')>0);assert.equal(run('prefs.best'),best);run('prefs.sensitivity=1;start()');assert.ok(!run('g.demo'))});
console.log(`${passed} tests passed`);
